version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=test

  prettier:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
    command: ["npm", "run", "prettier"]
